### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by sjraaijmakers** [rkalis/monokalis-syntax#1]
When using monokalis the current line working on is highlighted by a white background. Now, when you select a word on that same line, only this word will have a highlighted background (instead of the whole line), which is a bit confusing to me. So I'd suggest to keep the whole current line highlighted (when a word is selected) but mark the selected word with a different highlight.

**Comment by rkalis** [comment]
It seems that this is a limitation/feature of vanilla Atom. Once you select a piece of text, Atom loses its cursor-line attribute. The [highlight-line](https://atom.io/packages/highlight-line) package seems to solve this issue. I added support for this package in the next patch, so if you download the package it should fit right in with the rest of the theme. Thanks for your feedback!
