### ISSUE TITLE
Deprecated selectors Atom 1.13.0

### ISSUE THREAD

**Issue by marcusvb** [rkalis/monokalis-syntax#3]
Some of the monokalis code is deprecated and needs to be updated. Running Atom gives the following warning:

Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:...

**Comment by rkalis** [comment]
Updated the new selectors
